config:
  root_domain: webb.app
  root_domain_email: "adrian@webb.sh"

  aws_networks:
    - aws-us-east-1

  admin_host_name: admin

  cenv_database: "%%cenv_database:30"
  cenv_database_user: "%%cenv_database_user:30"
  cenv_password: "%%cenv_password:30"
